name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos-latest:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: brew install
      run: brew install pango gtk4
    - name: Stable
      run: |
        cargo test
    - name: Oldstable
      run: |
        rustup default 1.57.0
        cargo test
    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy --all-targets
  build-windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: pacman -S
      run: pacman -S mingw-w64-x86_64-gtk4
    - name: Stable
      run: |
        cargo test
    - name: Oldstable
      run: |
        rustup default 1.57.0
        cargo test
    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy --all-targets



